htmx_test/basic/urls.py
from django.urls import path

from . import views
from .views import OrganisationCreateView, PersonCreateView

app_name = "basic"
urlpatterns = [
    path("", views.index, name="index"),
    path("add/", PersonCreateView.as_view(), name="person-add"),
    path("orgadd/", OrganisationCreateView.as_view(), name="organisation-add"),
]

htmx_test/htmx_test/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('basic.urls')),
]

htmx_test/basic/models.py
from django.db import models


class Organisation(models.Model):
    ORG_CHOICES = [
        ("ORG1", "ORG1"),
        ("ORG2", "ORG2"),
    ]
    name = models.CharField(max_length=100)
    type = models.CharField(max_length=4, choices=ORG_CHOICES)
    location = models.CharField(max_length=100)

    def __str__(self):
        return self.name

    def __repr__(self):
        return f"Organisation(id={self.id}, name='{self.name}', type='{self.type}', location='{self.location}')"


class Person(models.Model):
    first_name = models.CharField(max_length=100)
    surname = models.CharField(max_length=100)
    email_address = models.EmailField(null=True, blank=True)
    organisation = models.ForeignKey(Organisation, on_delete=models.CASCADE, null=True)

    def __str__(self):
        return f"{self.first_name} {self.surname}"

    def __repr__(self):
        return f"Person(id={self.id}, first_name='{self.first_name}', surname='{self.surname}', email_address='{self.email_address}', organisation_id={self.organisation_id})"

htmx_test/basic/forms.py
from django import forms
from django.forms import ModelForm

from .models import Organisation, Person


class OrganisationForm(ModelForm):
    class Meta:
        model = Organisation
        fields = ("name", "type", "location")


class PersonCreateForm(ModelForm):
    class Meta:
        model = Person
        fields = ("first_name", "surname", "email_address", "organisation")
        widgets = {
            "organisation": forms.Select(attrs={"class": "form-control"}),
        }

htmx_test/basic/views.py
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic.edit import CreateView

from .forms import PersonCreateForm
from .models import Organisation, Person


def index(request):
    people = Person.objects.all()
    return render(request, "basic/index.html", context={"people": people})


class PersonCreateView(CreateView):
    model = Person
    form_class = PersonCreateForm
    success_url = reverse_lazy("basic:index")


class OrganisationCreateView(CreateView):
    model = Organisation
    fields = ["name", "type", "location"]
    template_name = "basic/organisation_create.html"
    success_url = reverse_lazy("basic:person-create")

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.prefix = "org"

    def form_valid(self, form):
        response = super().form_valid(form)
        self.object.save()
        return response

htmx_test/basic/templates/basic/base.html
{% load static %}

<html lang="en">
  <head>
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'basic/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'basic/style.css' %}">
  </head>
  <body>
    {% block content %}
    {% endblock %}
    <script src="{% static 'basic/js/bootstrap.min.js' %}"></script>
  </body>
</html>

htmx_test/basic/templates/basic/index.html
{% extends "basic/base.html" %}
{% block title %}Home page{% endblock %}
{% block content %}
<h1>People</h1>

<ul>
{% for person in people %}
<li>{{ person.first_name }} {{ person.surname }}</li>
{% endfor %}
</ul>

<a href="{% url 'basic:person-add' %}">Add a person here</a>

{% endblock %}

htmx_test/basic/templates/basic/organisation_create.html
{% extends "basic/base.html" %}
{% block title %}Create new organisation{% endblock %}
{% block content %}
  <form method="post" class="needs-validation" novalidate>
    {% csrf_token %}
    {{ org_form.as_p }}
    <button class="btn btn-primary" type="submit">Create organisation</button>
  </form>
{% endblock %}

htmx_test/basic/templates/basic/person_form.html
{% extends "basic/base.html" %}
{% block title %}Create new person{% endblock %}
{% block content %}
<form action="{% url 'basic:person-add' %}" method="post">
  {% csrf_token %}
  <fieldset> 
    <legend>
      <h1>New person</h1>
    </legend>
    {{ form.as_p }}
  <!-- Button trigger modal -->
  <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#new-org-modal">
	Launch modal
  </button>
  </fieldset>
  <input type="submit" value="Submit">
</form>

<!-- Modal -->
<div class="modal fade" id="new-org-modal" tabindex="-1" role="dialog" aria-labelledby="new-org-modal-label" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <form action="{% url 'basic:organisation-add' %}" method="post">
        {% csrf_token %}
        <div class="modal-header">
          <h5 class="modal-title" id="new-org-modal-label">Create new organization</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
          {{ org_form.as_p }}
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
          <button type="submit" class="btn btn-primary">Create organization</button>
        </div>
      </form>
    </div>
  </div>
</div>

{% endblock content %}